### ISSUE TITLE
Usage of static analysis tools

### ISSUE THREAD

**Issue by ricohumme** [mtarld/symbok-bundle#35]
Hi,

Has this bundle been tested by anyone using static analysis tools like `phan` and `phpstan` ?
I was just wondering because we use this and would hate to find out at a later stage that this bundle would break the analysis procedure.

Thanks in advance!

**Comment by mtarld** [comment]
Hi @ricohumme,

Yes it should work, but you'll have to do little adaptations because getters/setters are not really written as you may know.

### PHPMD
You'll have to ignore unused private fields in processed classes
```php
/**
 * @SuppressWarnings(PHPMD.UnusedPrivateField)
 */
class Foo
{
    /**
     * @Getter
     */
    private $bar;
}
```
Or more generally in your phpmd.xml:
```xml
<rule ref="rulesets/unusedcode.xml">
    <exclude name="UnusedPrivateField" />
</rule>
```

### PHPStan
You will have an error like `Call to an undefined method App\Entity\Foo::getBar()`.

It's because PHPStan cannot know that `getBar` method exists. 

You'll have to run `symbok:update:classes` command. This command will add a `@method` tag to your class (see [the doc](https://github.com/mtarld/symbok-bundle/blob/master/src/Resources/doc/commands.md))

### Phan
You will have an error like `PhanUndeclaredMethod Call to undeclared method \App\Entity\Foo::getBar`. Same as PHPStan, it's because Phan cannot know that `getBar` method exists. 

You'll have to run `symbok:update:classes` command. This command will add a `@method` tag to your class (see [the doc](https://github.com/mtarld/symbok-bundle/blob/master/src/Resources/doc/commands.md))

You will also have an error like `PhanUnreferencedUseNormal Possibly zero references to use statement for classlike/namespace Symbok (\Mtarld\SymbokBundle\Annotation\Getter)` which is a common issue of phan with annotations.

It could be resolved by installing [drenso/phan-extensions](https://github.com/Drenso/PhanExtensions#annotationsymfonyannotationplugin) (see [the issue](https://github.com/phan/phan/issues/1757))

---
Btw, while testing, I've found that the bundle does not work using non-standard
annotations such as `@SuppressWarnings`. I'll fix it ASAP (related issue: https://github.com/mtarld/symbok-bundle/issues/36)
